DROP TABLE IF EXISTS posts;

CREATE TABLE budget (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category TEXT NOT NULL,
    notes TEXT NOT NULL,
    dollar INT DEFAULT 0
);